apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: myselfabii/mern-backend:latest
        ports:
        - containerPort: 5001
        env:
        - name: MONGODB_URI
          value: mongodb://root:example@mongodb:27017/mern-crud?authSource=admin
        - name: PORT
          value: "5001"
        - name: NODE_ENV
          value: "production"
        - name: CORS_ORIGIN
          value: "*"
        - name: CORS_METHODS
          value: "GET,HEAD,PUT,PATCH,POST,DELETE"
        - name: CORS_CREDENTIALS
          value: "true"
        - name: CORS_ALLOWED_HEADERS
          value: "Content-Type,Authorization"
        - name: CORS_EXPOSED_HEADERS
          value: "Content-Range,X-Content-Range"
        - name: CORS_MAX_AGE
          value: "86400" 