apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::814022331516:role/general-eks-node-group-20250509204528423600000001
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::814022331516:role/eks-admin-role
      username: admin
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::814022331516:user/cli-user
      username: admin
      groups:
        - system:masters
