{{- if and .Values.mongodb.enabled .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongodb-pvc
  labels:
    {{- include "mern-stack.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mongodb.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size | quote }}
  {{- if .Values.mongodb.persistence.storageClass }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
  {{- end }}
{{- end }} 