{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    {{- include "mern-stack.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mern-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
  ports:
  - port: 27017
    targetPort: mongodb
    protocol: TCP
    name: mongodb
  clusterIP: None
{{- end }} 