# Global settings
nameOverride: ""
fullnameOverride: ""
image:
  registry: "myselfabii/"
  pullPolicy: IfNotPresent

# MongoDB settings
mongodb:
  enabled: true
  replicaCount: 1
  image:
    repository: mongo
    tag: latest
  persistence:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: ""
  auth:
    username: root
    password: example
    database: mern-crud
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

# Backend settings
backend:
  enabled: true
  replicaCount: 2
  image:
    repository: mern-backend
    tag: latest
  service:
    type: ClusterIP
    port: 5001
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

# Frontend settings
frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: mern-frontend
    tag: latest
  service:
    type: LoadBalancer
    port: 80
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

# Ingress settings
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
          serviceName: mern-stack-frontend
          servicePort: 80
        - path: /api
          pathType: Prefix
          serviceName: mern-stack-backend
          servicePort: 5001
  tls: [] 